sudo: false
language: c
compiler:
    - clang
    - gcc
os:
    - linux
    - osx
install:
        - ./autogen.sh
        - ./configure --prefix=$HOME
        - make -j2
        - make install
        - make test
        - make distcheck
script:
        - git clone https://github.com/ofiwg/fabtests.git
        - cd fabtests
        - ./autogen.sh
        - ./configure --prefix=$HOME --with-libfabric=$HOME
        - make -j2
        - make install
        - make test
