sudo: false
language: c
compiler:
    - clang
    - gcc
os:
    - linux
    - osx
matrix:
  exclude:
    - os: osx
      compiler: gcc
  fast_finish: true

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
install: ./autogen.sh
script: ./configure --prefix=${TRAVIS_BUILD_DIR}/install_dir &&
         make install V=1 && ${TRAVIS_BUILD_DIR}/install_dir/bin/fi_info -v

