language: c

compiler:
  - gcc

before_install:
  - git clone https://github.com/bturrubiates/ugni-build.git;
    pushd ugni-build;
    tar -xf ugni.build.tgz;
    pushd ugni-build;
    sudo tar -C / -xzvf opt-cray.tgz;
    source set_pkg_path.sh;
    popd;
    popd

os:
  - linux

script: ./autogen.sh && ./configure && make V=1
